### ISSUE TITLE
[Maybe Regression](only in PROD on Vercel!) mywebsite.com/robots.txt | mywebsite.com/sitemap.xml triggers "A proper locale must be provided" error

### ISSUE THREAD

**Issue by gustaveWPM** [QuiiBz/next-international#299]
When I go on https://dashboard-rtm.vercel.app/sitemap.xml
Or https://dashboard-rtm.vercel.app/robots.txt

It triggers the following error:

```
bel+core@7.23.3_@opentelemetry+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:129267)
    at listOnTimeout (node:internal/timers:569:17)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '2208410778'
}
 ⨯ RangeError: A proper locale must be provided
    at new a (/var/task/.next/server/chunks/30.js:1:207103)
    at T (/var/task/.next/server/chunks/700.js:1:31517)
    at em (/var/task/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_@opentelemetry+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128381)
    at /var/task/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_@opentelemetry+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:140081
    at Array.toJSON (/var/task/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_@opentelemetry+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:143659)
    at stringify (<anonymous>)
    at eE (/var/task/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_@opentelemetry+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132044)
    at eR (/var/task/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_@opentelemetry+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132487)
    at Timeout._onTimeout (/var/task/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_@opentelemetry+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:129267)
    at listOnTimeout (node:internal/timers:569:17) {
  page: '/sitemap.xml'
}
RangeError: A proper locale must be provided
    at new a (/var/task/.next/server/chunks/30.js:1:207103)
    at T (/var/task/.next/server/chunks/700.js:1:31517)
    at em (/var/task/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_@opentelemetry+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128381)
    at /var/task/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_@opentelemetry+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:140081
    at Array.toJSON (/var/task/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_@opentelemetry+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:143659)
    at stringify (<anonymous>)
    at eE (/var/task/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_@opentelemetry+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132044)
    at eR (/var/task/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_@opentelemetry+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132487)
    at Timeout._onTimeout (/var/task/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_@opentelemetry+api@1.7.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:129267)
    at listOnTimeout (node:internal/timers:569:17) {
  page: '/sitemap.xml'
}
Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Notice that it could also be a Next.js/Vercel regression.
I can't reproduce this locally, localhost:3000/sitemap.xml | localhost:3000/robots.txt works as intended.

However, the error which is raised is from next-international.

**Comment by gustaveWPM** [comment]
Hum, well. It seems to be my fault, sorry. I forgot to review the Deployment Details, and strangely, `next-sitemap` is not executed on my deploys. o_O

Closing for now.
