### ISSUE TITLE
Example for Storybook

### ISSUE THREAD

**Issue by WilhelmHjelm** [QuiiBz/next-international#355]
Could you please give an example or preferred way to use <I18nProvider> while using Storybook? I try to add <I18nProvider> to my preview.tsx in storybook but no components render inside and I get an error in the console that my locales aren't defined in next.config.js. They are and I use @storybook/nextjs as framework for Storybook which should make next.config.js available in Storybook.

**Comment by gustaveWPM** [comment]
> Could you please give an example or preferred way to use while using Storybook? I try to add to my preview.tsx in storybook but no components render inside and I get an error in the console that my locales aren't defined in next.config.js. They are and I use @storybook/nextjs as framework for Storybook which should make next.config.js available in Storybook.

Hello, please could you provide a minimalist reproduction?

**Comment by WilhelmHjelm** [comment]
> > Could you please give an example or preferred way to use while using Storybook? I try to add to my preview.tsx in storybook but no components render inside and I get an error in the console that my locales aren't defined in next.config.js. They are and I use @storybook/nextjs as framework for Storybook which should make next.config.js available in Storybook.
> 
> Hello. Please, could you provide a minimalist reproduction?

This is my preview.tsx file in Storybook. It gives 0 type errors but in the console we get an error saying `[next-international] 'i18n.defaultLocale' not defined in 'next.config.js'`. And a warning `[next-international] The following locales are defined in 'createI18n' but not in 'next.config.js': en, sv, no, da, de, fi`. And nothing is rendered as children through `<I18nProvider>`. Not even the fallback prop.

``` preview.tsx
import { Preview } from '@storybook/react'
import React from 'react'
import { I18nProvider } from '../locales'
import en from '../locales/dictionaries/en'

const preview: Preview = {
  decorators: [
    (Story) => (
      <main>
        <I18nProvider locale={en} fallback={<p>Fallback</p>}>
          <Story />
        </I18nProvider>
      </main>
    )
  ]
}
```

**Comment by gustaveWPM** [comment]
That's weird...
I guess you are using the pages router?

Also, I don't think Storybook is causing the issue here...

Maybe you've missed something during the configuration?
I'm thinking about this: https://github.com/QuiiBz/next-international/issues/350

**Comment by WilhelmHjelm** [comment]
Very weird indeed, since it works perfectly fine in the Next.js app. 

Yes, pages router. This is the i18n section of my `next.config.js`. 

``` .js
  i18n: {
    locales: ['en', 'sv', 'no', 'da', 'de', 'fi'],
    defaultLocale: 'en',
    localeDetection: false
  },
```

also, this is my `locales/index.ts`

``` .js
import { createI18n } from 'next-international'

export const { useI18n, useScopedI18n, I18nProvider, getLocaleProps } =
  createI18n({
    en: () => import('./dictionaries/en'),
    sv: () => import('./dictionaries/sv'),
    no: () => import('./dictionaries/no'),
    da: () => import('./dictionaries/da'),
    de: () => import('./dictionaries/de'),
    fi: () => import('./dictionaries/fi')
  })
```

**Comment by gustaveWPM** [comment]
Hmmm... I've never experienced Next International with the _Pages Router_... :/
Hope someone else can help!

**Comment by WilhelmHjelm** [comment]
Found a solution! `@storybook/next` gives you the ability to "mock the next/router". Just add the same i18n configs as in your `next.config.js` in your storybook/preview.tsx like this: 

``` .tsx
const preview: Preview = {
  parameters: {
    nextjs: {
      router: {
        locale: 'en',
        locales: ['en', 'sv', 'no', 'da', 'de', 'fi'],
        defaultLocale: 'en'
      }
    },

...
```

**Comment by gustaveWPM** [comment]
> Found a solution! `@storybook/next` gives you the ability to "mock the next/router". Just add the same i18n configs as in your `next.config.js` in your storybook/preview.tsx like this:
> 
> ```tsx
> const preview: Preview = {
>   parameters: {
>     nextjs: {
>       router: {
>         locale: 'en',
>         locales: ['en', 'sv', 'no', 'da', 'de', 'fi'],
>         defaultLocale: 'en'
>       }
>     },
> 
> ...
> ```

I'm very glad to know it's solved!
Is it possible to rename the issue to point out the lack of documentation about it?

I'd be happy to take the code snippets you shared and add a documentation page this weekend.

**Comment by QuiiBz** [comment]
That would be very appreciated @gustaveWPM!

**Comment by gustaveWPM** [comment]
I'm still on it, sorry for the delay!
I'll do it. I just had a few setbacks. Sorry about that.

**Comment by baixiaoyu2997** [comment]
i use `output: 'export',` in next config

when i  use `useCurrentLocale()` will cause error: `NEXT_HTTP_ERROR_FALLBACK;404`

```
The component failed to render properly, likely due to a configuration issue in Storybook. Here are some common causes and how you can address them:

Missing Context/Providers: You can use decorators to supply specific contexts or providers, which are sometimes necessary for components to render correctly. For detailed instructions on using decorators, please visit the [Decorators documentation](https://storybook.js.org/docs/writing-stories/decorators).
Misconfigured Webpack or Vite: Verify that Storybook picks up all necessary settings for loaders, plugins, and other relevant parameters. You can find step-by-step guides for configuring [Webpack](https://storybook.js.org/docs/builders/webpack) or [Vite](https://storybook.js.org/docs/builders/vite) with Storybook.
Missing Environment Variables: Your Storybook may require specific environment variables to function as intended. You can set up custom environment variables as outlined in the [Environment Variables documentation](https://storybook.js.org/docs/configure/environment-variables).
Error: NEXT_HTTP_ERROR_FALLBACK;404
    at notFound (http://localhost:6006/vendors-node_modules_mui_material_CssBaseline_CssBaseline_js-node_modules_mui_material_styles-20735e.iframe.bundle.js:26780:19)
    at mockCall (http://localhost:6006/vendors-node_modules_mui_material_CssBaseline_CssBaseline_js-node_modules_mui_material_styles-20735e.iframe.bundle.js:12843:5296)
    at http://localhost:6006/vendors-node_modules_mui_material_CssBaseline_CssBaseline_js-node_modules_mui_material_styles-20735e.iframe.bundle.js:12877:15267
    at notFound (http://localhost:6006/vendors-node_modules_mui_material_CssBaseline_CssBaseline_js-node_modules_mui_material_styles-20735e.iframe.bundle.js:12843:2704)
    at http://localhost:6006/vendors-node_modules_mui_material_CssBaseline_CssBaseline_js-node_modules_mui_material_styles-20735e.iframe.bundle.js:26017:39
    at mountMemo (http://localhost:6006/vendors-node_modules_storybook_react-dom-shim_dist_react-18_mjs.iframe.bundle.js:5749:23)
    at Object.useMemo (http://localhost:6006/vendors-node_modules_storybook_react-dom-shim_dist_react-18_mjs.iframe.bundle.js:22794:18)
    at push../node_modules/next/dist/compiled/react/cjs/react.development.js.exports.useMemo (http://localhost:6006/vendors-node_modules_mui_material_CssBaseline_CssBaseline_js-node_modules_mui_material_styles-20735e.iframe.bundle.js:32358:34)
    at useCurrentLocale (http://localhost:6006/vendors-node_modules_mui_material_CssBaseline_CssBaseline_js-node_modules_mui_material_styles-20735e.iframe.bundle.js:26010:38)
    at useI18nRouter (http://localhost:6006/src_stories_utils_tsx.cd4d27677d4fc977de35.hot-update.js:23:85)
```
