### ISSUE TITLE
App Router: SSG not working as described in docs

### ISSUE THREAD

**Issue by smoxx** [QuiiBz/next-international#84]
Hello,

I was trying to get SSG working in the app router and did the required things like described in the docs.
I uncommented:
`export const generateStaticParams = getStaticParams();` in app/[locale]/page.tsx, as well as:
`  output: "export"` in the next.config.js

when i now run the next build command, I get the following error

```
> next build

- info Creating an optimized production build  
- info Compiled successfully
- info Skipping validation of types
- info Skipping linting
- info Collecting page data  
- info Generating static pages (3/3)
- info Finalizing page optimization  

Route (app)                                Size     First Load JS
┌ λ /[locale]                              140 B          78.4 kB
├ λ /[locale]/client                       2.52 kB        80.7 kB
├ λ /[locale]/subpage                      140 B          78.4 kB
└ ○ /favicon.ico                           0 B                0 B
+ First Load JS shared by all              78.2 kB
  ├ chunks/437-f84f08f412263f07.js         25.8 kB
  ├ chunks/d909b7fe-b8be5e5e0523de08.js    50.5 kB
  ├ chunks/main-app-314d6406b014043c.js    214 B
  └ chunks/webpack-d41e780fcf98ea6d.js     1.74 kB

Route (pages)                              Size     First Load JS
─ ○ /404                                   182 B          75.8 kB
+ First Load JS shared by all              75.6 kB
  ├ chunks/framework-510ec8ffd65e1d01.js   45 kB
  ├ chunks/main-f3d726c6da438ade.js        28.6 kB
  ├ chunks/pages/_app-4fa603cb0fa6e977.js  196 B
  └ chunks/webpack-d41e780fcf98ea6d.js     1.74 kB

ƒ Middleware                               19.5 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)

StaticGenBailoutError: Page with `dynamic = "error"` couldn't be rendered statically because it used `headers`.
    at staticGenerationBailout (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/661.js:152:15)
    at headers (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/483.js:84:62)
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:91:27
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/299.js:7641:23
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:100:21
    at Generator.next (<anonymous>)
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:53:31
    at new Promise (<anonymous>)
    at f (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:39:20)
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:99:16 {
  code: 'NEXT_STATIC_GEN_BAILOUT'
}
StaticGenBailoutError: Page with `dynamic = "error"` couldn't be rendered statically because it used `headers`.
    at staticGenerationBailout (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/661.js:152:15)
    at headers (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/483.js:84:62)
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:91:27
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/299.js:7641:23
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:100:21
    at Generator.next (<anonymous>)
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:53:31
    at new Promise (<anonymous>)
    at f (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:39:20)
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:99:16 {
  code: 'NEXT_STATIC_GEN_BAILOUT'
}
Error: Locale not found
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/299.js:158:19
    at Object.ye [as useMemo] (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:101:241)
    at exports.useMemo (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react/cjs/react.production.min.js:29:208)
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/299.js:156:30
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/299.js:66:17
    at Ue (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:113:273)
    at Z (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:120:91)
    at Ue (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:114:9)
    at Ue (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:119:11)
    at Z (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:120:91)

Error occurred prerendering page "/[locale]/subpage". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Page with `dynamic = "error"` couldn't be rendered statically because it used `headers`.
    at staticGenerationBailout (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/661.js:152:15)
    at headers (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/483.js:84:62)
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:91:27
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/299.js:7641:23
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:100:21
    at Generator.next (<anonymous>)
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:53:31
    at new Promise (<anonymous>)
    at f (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:39:20)
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:99:16

Error occurred prerendering page "/[locale]/client". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Locale not found
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/299.js:158:19
    at Object.ye [as useMemo] (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:101:241)
    at exports.useMemo (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react/cjs/react.production.min.js:29:208)
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/299.js:156:30
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/299.js:66:17
    at Ue (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:113:273)
    at Z (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:120:91)
    at Ue (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:114:9)
    at Ue (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:119:11)
    at Z (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:120:91)

Error occurred prerendering page "/[locale]". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Page with `dynamic = "error"` couldn't be rendered statically because it used `headers`.
    at staticGenerationBailout (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/661.js:152:15)
    at headers (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/483.js:84:62)
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:91:27
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/299.js:7641:23
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:100:21
    at Generator.next (<anonymous>)
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:53:31
    at new Promise (<anonymous>)
    at f (/Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:39:20)
    at /Users/smox/Developer/WebDev/Multilanguage Testing/next-international/.next/server/chunks/973.js:99:16

> Export encountered errors on following paths:
        /[locale]/client/page: /[locale]/client
        /[locale]/page: /[locale]
        /[locale]/subpage/page: /[locale]/subpage
 ELIFECYCLE  Command failed with exit code 1.
```

I don't know if I simply missed something or what else the source of this error could be. 
I would be very thankful if you could help me figure this out.

**Comment by QuiiBz** [comment]
Hi, unfortunately, SSG isn't possible within the App Router right now (that's why it's written WIP in the 3rd step https://github.com/QuiiBz/next-international#app-router). This is due to a limitation that Server Components can't use `useParams` / `usePathname`, and since it's SSG it also can't use `cookies()` or `headers()` to retrieve the locale.

This situation impacts other i18n libraries but I'm hoping to see it resolved soon.

**Comment by smoxx** [comment]
Thank you very much for your answer. I guess I'll just have to wait a little more.
